# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4ce95f127275f60511ce85786e759ce18340096793620bcb5bafe5ae6c2dbafeb16434d1bfdc486337692ef19210f36f0b868f4e3896181c8fb15178f5d17b4

test:
  secret_key_base: d867e09a99d7ee70bd95c9f45abd2ccb73a2cafa482cdf92f2c2982e7f11cccc76ee87e63a10d6c4bab0b5b62679b4f78a363ff92aada7ccbd05d52492938131

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
